### ISSUE TITLE
Set custom flags

### ISSUE THREAD

**Issue by victormihalache** [siddhantac/puffin#38]
I wanted to make an issue to have the cost reporting, but, wouldn't it be simpler to have for each report a key you can press that allows you to type what flags puffin should append to the call to hledger? This would allow the user to have it so they can have report the way they want it—with the beauty of puffin, even if the feature isn't directly supported by puffin.

[GitUI](https://github.com/extrawurst/gitui) does this in the way I would expect it to. When you're in the commits tab...

<img width="1018" alt="Screenshot 2024-06-20 at 17 48 46" src="https://github.com/siddhantac/puffin/assets/82441538/92e5a6be-6965-4175-8880-d040725a88ff">

...you can press `t` and the input field pops up for you to type.

<img width="1018" alt="Screenshot 2024-06-20 at 17 48 54" src="https://github.com/siddhantac/puffin/assets/82441538/b98f7042-6c40-4941-a2de-74f40479fbb8">

**Comment by siddhantac** [comment]
Thanks for the suggestion! As far as I can tell, Gitui is only allowing you to add tags in the second screenshot.

In general, I am trying to keep Puffin focused, with specific keys to activate flags or settings. 

I'll be working on cost reporting (`--cost`) and value reporting (`--marketing`) next, since there seems to be some interest around those topics. (see #42 )

Having said that, I do think there might be some value in adding more customisability. I'm playing around with some ideas with that, so hopefully I'll have an update for it in the future.

**Comment by siddhantac** [comment]
You can create your own reports with custom flags now via a config file. (see release v1.7.0)
