### ISSUE TITLE
Option to filter by commodity / currency

### ISSUE THREAD

**Issue by piero-vic** [siddhantac/puffin#51]
Hi.

First of all, thank you for the great tool. It has been very useful.

I'm currently working with multiple currencies. It would be nice to generate reports targeting a specific currency.

I believe this could be done by using `hledger commodities` to list available options and a currency query (e.g., `hledger cur:<currency>`) when generating reports.

**Comment by siddhantac** [comment]
You're welcome!

With the latest update, you can setup your own custom reports. I am yet to work on the documentation. But you can simply copy the `config.debug.json` file and setup reports as you wish. If you set `locked` to `true` then the filters in the app won't affect that report.

If you follow this approach, do let me know how it goes!

**Comment by phobo3s** [comment]
i tried the locked method but it seems it is not working. or am i missing something.
![image](https://github.com/user-attachments/assets/35c6f406-56ae-40ba-b382-96ad3dd68510)
the command still follows the filter year 2022. i have records before that.

**Comment by siddhantac** [comment]
@phobo3s I have made some major changes. The `locked` option should work now. Please try with the latest release [v2.0.0-rc](https://github.com/siddhantac/puffin/releases/tag/v2.0.0-rc).

You can try it with this config file [config.debug.json](https://github.com/siddhantac/puffin/blob/main/config.debug.json).

*Note*:
1. This is only supported for `balance` reports currently
1. By default, it will show the balance report in table format with graphs (show/hide graph with `g`)
2. To show the report in native hledger format, use `locked: true`. This will cause puffin to treat the hledger output as is, without any modification.

@piero-vic I think this would solve your issue with the `commodity` report as well. Since `commodity` isn't supported exclusively yet, setting `locked` field has no effect on it. It will always be treated as if it is locked.

**Comment by phobo3s** [comment]
yessss. Very Very good. i can get balancesheet report without yearly. 
it is perfect, thank you. But graph not visible on windows.

**Comment by siddhantac** [comment]
thanks @phobo3s . I opened a new issue for that https://github.com/siddhantac/puffin/issues/61
